spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    name: datasource
    initialize: true
    url: jdbc:mysql://localhost:3306/eshop_product?characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    max-active: 200
    max-idle: 50
    min-idle: 10
    initial-size: 10
    validation-query: select 1
    test-on-borrow: true
    test-on-return: false
    test-while-idle: false
    time-between-eviction-runs-millis: 3000
    min-evictable-idle-time-millis: 3000
    max-wait: 3000
    jmx-enabled: true


server:
  port: 8765
  tomcat:
    accesslog:
      directory: "/tmp/eshop"
      enabled: true
      pattern: '%{X-Forwarded-For}i %h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D'
      rotatable: true
      prefix: "eshop"
      suffix: ".log"


mybatis:
  check-config-location: true
  typeAliasesPackage: com.junlong.eshop.entity
  mapperLocations: classpath:mybatis/xml/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml

